# Generated by Django 5.0.4 on 2024-11-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=0)),
                ('joylashuvi_viloyat', models.CharField(max_length=500)),
                ('joylashuvi_shahar', models.CharField(max_length=500)),
                ('joylashuvi_mahallasi', models.CharField(max_length=200)),
                ('joylashuvi_uy', models.CharField(max_length=200)),
                ('joy_izoh', models.CharField(max_length=200)),
                ('malumotlar_list_id', models.IntegerField()),
                ('vaqt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='mini_card_and_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls_nomi', models.CharField(max_length=100)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='mini_card/')),
            ],
        ),
        migrations.CreateModel(
            name='Taomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=100)),
                ('mahsulot_izohi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='fayl/')),
                ('mahsulot_narxi', models.IntegerField(blank=True, null=True)),
                ('mahsulot_turi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=1)),
            ],
        ),
    ]
